print("hello m.6/11")
print("My name is Sirisak Phanawan")
print("No.10") 
print("บ้านอยู่ศรีราชา")
print("เลือดกรุ๊ป o")
print("เพศชาย")
print("ได้เงินมาโรงเรียน160บาท")
print("สูง176ซม.")
print("น้ำหนัก60")
print("สัญชาติไทย")